### PR TITLE
Add dev dependency, exclude lib/ from SCM, remove console.log

### PR DESCRIPTION
**Pull request by eagleoflqj**

### CODE REVIEW

**Comment by justforuse** [comment]
@eagleoflqj Why remove `lib/`? I think that is the file that referred in `package.json` file

**Comment by eagleoflqj** [comment]
Automatically generated files (except package-lock.json) should be excluded from source code management.

**Comment by justforuse** [comment]
@eagleoflqj Thanks your job! I spent few days to check how the well-known packages do this staff by [jsdelivr](https://www.jsdelivr.com/package/npm/vue), I misunderstood first😅, so you mean that the `lib` files should not be push to github, it should published by owner?

**Comment by eagleoflqj** [comment]
> so you mean that the `lib` files should not be push to github, it should published by owner?

Exactly! I do see repos like [vueuc](https://github.com/07akioni/vueuc/blob/main/package.json) that excludes lib/ from git but has `"main": "lib/index.js"` in package.json

**Pull request merged**
